name: emo_probe
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=26.2.0=py312h6a678d5_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.10.1
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - babe==0.0.7
      - beartype==0.14.1
      - better-abc==0.0.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - config2py==0.1.38
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - docstring-parser==0.17.0
      - dol==0.3.20
      - einops==0.8.1
      - fancy-einsum==0.0.3
      - filelock==3.13.1
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graze==0.1.31
      - h5py==3.14.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - i2==0.1.48
      - idna==3.10
      - importlib-resources==6.5.2
      - jaxtyping==0.3.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - narwhals==2.4.0
      - networkx==3.3
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.14.1.1
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.9.79
      - pandas==2.3.2
      - patsy==1.0.1
      - pillow==11.0.0
      - plotly==6.3.0
      - plotly-express==0.4.1
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - py2store==0.1.21
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - sae-lens==6.11.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - sentence-transformers==5.1.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.36.0
      - simple-parsing==0.1.7
      - smmap==5.0.2
      - statsmodels==0.14.5
      - sympy==1.13.3
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.0
      - torch==2.8.0+cu129
      - torchvision==0.23.0+cu129
      - tqdm==4.67.1
      - transformer-lens==2.16.1
      - transformers==4.56.0
      - transformers-stream-generator==0.0.5
      - triton==3.4.0
      - typeguard==4.4.4
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - wandb==0.21.3
      - xxhash==3.5.0
      - yarl==1.20.1
